config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('', base_views.index, name='index'),         # '/'에 해당하는 path

]

pybo/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import base_views, question_views, answer_views, comment_views, vote_views

app_name = 'pybo'

urlpatterns = [

    # base_views.py
    path('',
         base_views.index, name='index'),
    path('<int:question_id>/',
         base_views.detail, name='detail'),

    # question_views.py
    path('question/create/',
         question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/',
         question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/',
         question_views.question_delete, name='question_delete'),

    # answer_views.py
    path('answer/create/<int:question_id>/',
         answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/',
         answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/',
         answer_views.answer_delete, name='answer_delete'),

    # comment_views.py
    path('comment/create/question/<int:question_id>/',
         comment_views.comment_create_question, name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/',
         comment_views.comment_modify_question, name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/',
         comment_views.comment_delete_question, name='comment_delete_question'),
    path('comment/create/answer/<int:answer_id>/',
         comment_views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/',
         comment_views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/',
         comment_views.comment_delete_answer, name='comment_delete_answer'),

    # vote_view.py
    path('vote/question/<int:question_id>',vote_views.vote_question ,name='vote_question'),
    path('vote/answer/<int:answer_id>', vote_views.vote_answer, name='vote_answer'),

]
'''
제너릭 뷰 url

from django.urls import path

from . import views

app_name = 'pybo'
urlpatterns = [
    path('', views.IndexView.as_view()),
    path('<int:pk>/', views.DetailView.as_view()),
]
'''

pybo/models.py
from django.db import models

# Create your models here.

from django.db import models
from django.contrib.auth.models import User

class Question(models.Model):

    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_question')
    # models.CASCADE: 계정이 삭제되면 계정과 연결된 Question 모델 데이터를 모두 삭제
    #author 추가한 후 makemigrations 하면 오류 생김,름
    # Question 모델에 author 필드를 추가하면 이미 등록되어 있던 게시물에 author 필드에 해당되는 값이 저장되어야 하는데,
    # 장고는 author 필드에 어떤 값을 넣어야 하는지 모름
    # 해결하는 방법에는 2가지가 있다. 첫 번째 방법은 author 필드를 null로 설정하는 방법이고,
    # 두 번째 방법은 기존 게시물에 추가될 author 필드의 값에 강제로 임의 계정 정보를 추가하는 방법.
    # 질문, 답변에는 author 필드값이 무조건 있어야 하므로 두 번째 방법을 사용. 오류 메시지를 유지한 상태에서 '1'을 입력하고 엔터 두번 반복.
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modified_date = models.DateTimeField(null=True, blank=True) # 수정일시를 의미, null=True, blank=True는 어떤 조건으로든 값을 비워둘 수 있음
    voter = models.ManyToManyField(User, related_name='voter_question')    # voter 추가, 다대다 관계를 위 한 ManyToManyField
    # 추천은 질문이나 답변에 적용해야 하는 요소.
    # Question, Answer 모델에 추천인 필드 voter를 추가해야 한다.
    # 게시판 서비스를 사용해 봤다면 글 1개에 여러 명이 추천할 수 있고,
    # 반대로 1명이 여러 개의 글을 추천할 수 있음을 쉽게 알 수 있음.
    # 그리고 이런 경우에는 모델의 다대다(ManyToMany) 관계를 사용해야 한다.

    # Question 모델에서 사용한 author와 voter 필드가 모두 User 모델을 참조,
    # 추후 User.question_set과 같이 User 모델을 통해 Question 데이터에 접근할 경우 author 필드를 기준으로 할지 voter 필드를 기준으로 할지 장고는 알 수 없으므로
    # 직접 정하라는 뜻이다. related_name 옵션 추가로 해결할 수 있다.
    # author 필드에는 related_name='author_question'을 추가하고, voter 필드에는 related_name='voter_question'을 추가.
    # 이렇게 하면 특정 사용자가 작성한 질문을 얻기 위해 some_user.author_question.all(), some_user.voter_question.all() 같은 코드를 사용할 수 있다.
    def __str__(self):
         return self.subject

class Answer(models.Model):

    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_answer')
    # models.CASCADE: 계정이 삭제되면 계정과 연결된 Question 모델 데이터를 모두 삭제
    # author 추가한 후 makemigrations 하면 오류 생김,름
    # Question 모델에 author 필드를 추가하면 이미 등록되어 있던 게시물에 author 필드에 해당되는 값이 저장되어야 하는데,
    # 장고는 author 필드에 어떤 값을 넣어야 하는지 모름
    # 해결하는 방법에는 2가지가 있다. 첫 번째 방법은 author 필드를 null로 설정하는 방법이고,
    # 두 번째 방법은 기존 게시물에 추가될 author 필드의 값에 강제로 임의 계정 정보를 추가하는 방법.
    # 질문, 답변에는 author 필드값이 무조건 있어야 하므로 두 번째 방법을 사용. 오류 메시지를 유지한 상태에서 '1'을 입력하고 엔터 두번 반복.
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modified_date = models.DateTimeField(null=True, blank=True) # 수정일시를 의미, null=True, blank=True는 어떤 조건으로든 값을 비워둘 수 있음
    voter = models.ManyToManyField(User, related_name='voter_answer')





class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modified_date = models.DateTimeField(null=True, blank=True)
    question = models.ForeignKey(Question, on_delete=models.CASCADE, null=True, blank=True)
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE,null=True, blank=True)
    # 질문에 댓글을 작성하면 Comment 모델의 question 필드에 값이 저장되고,
    # 답변에 댓글이 작성되면 answer에 값이 저장.
    # 즉, Comment 모델 데이터에는 question 필드 또는 answer 필드 중 하나에만 값이 저장되므로
    # *두 필드는 모두 null=True, blank=True여야 한다.

pybo/forms.py
from django import forms
from pybo.models import Question, Answer, Comment

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['subject', 'content'] # 질문이 등록된 후 필드안의 속성들만 보여줌 (제목, 내용만), 개별적으로 정해짐

        labels = {
            'subject': '제목',
            'content': '내용',
        }

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content' : '답변내용',
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        labels = {
            'content': '댓글내용',
        }

pybo/views/answer_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone

from ..forms import AnswerForm
from ..models import Question, Answer



@login_required(login_url='common:login')
# 로그인이 안되어져있으면 로그인 화면으로 이동
# request.user가 User 객체가 아닌 AnonymousUser 객체면 오류 발생하므로 해당 어노태이션 필요
# 어노테이션 사용하면 로그아웃 상태에서 '질문 등록하기'를 눌러 로그인 화면으로 전환된 상태에서 웹 브라우저 주소창의 URL을 보면 next 파라미터가 있음.
# 이는 로그인 성공 후 next 파라미터에 있는 URL로 페이지를 이동해야 한다는 의미
# ****로그인 html 탬플릿에 <input type="hidden" name="next" value="{{ next }}"> 넣어줘 next url로 가짐.
def answer_create(request, question_id):

    question = get_object_or_404(Question, pk = question_id)
    if request.method == 'POST':
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.create_date = timezone.now()
            answer.question = question
            answer.author = request.user    # author에 유저정보 포함
            answer.save()
            return redirect('{}#answer_{}'.format(
                resolve_url('pybo:detail', question_id=question.id), answer.id))

    else:
        form = AnswerForm()

    context = {'question': question, 'form' : form}
    return render(request, 'pybo/question_detail.html', context)
    # answer는 유효성을 통과 못하는 경우가 아예 입력을 안하는 것 밖에 없어서 통과 못하면 그냥 공백 출력해주면 됨
    # 오류가 나도 내용을 유지할 필요 없으므로 form = AnswerForm() 부분이 굳이 필요하지는 않음
    # 그냥 추가해놓음
    # ***사용자 관점에서 메커니즘을 파악하고 코드를 구현하면 여러모로 비슷한 기능이라도 미묘한 차이가 발생.




@login_required(login_url='common:login')
def answer_delete(request, answer_id):

    answer = get_object_or_404(Answer, pk=answer_id)

    if request.user != answer.author:
        messages.error(request, '삭제권한이 없습니다.')
        return redirect('pybo:detail', question_id= answer.question.id)
    else:
        answer.delete()
    return redirect('pybo:detail', question_id=answer.question.id)




@login_required(login_url='common:login')
def answer_modify(request, answer_id):

    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '삭제권한이 없습니다.')
        return redirect('pybo:detail', question_id = answer.question.id)

    if request.method == 'POST':
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():

            answer = form.save(commit=False)
            answer.author = request.user
            answer.modified_date = timezone.now()
            answer.save()
            return redirect('{}#answer_{}'.format(
                resolve_url('pybo:detail', question_id=answer.question.id), answer.id))
    else:
        form = AnswerForm(instance=answer)
    context = {'form': form, 'answer':answer}
    return render(request, 'pybo/answer_form.html', context)

pybo/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from pybo.models import Question
from django.db.models import Q, Count


def index(request):

    '''pybo 목록 출력'''


    # 입력 파라미터
    # page는 html에서 다음페이지나 이전 페이지를 요청하면 주소뒤에 ?page=숫자 의 get 방식으로 던저줌
    # 만약 그냥 제일 처음 진입 하면 그냥 page는 1로 초기화 해줌 -> get('page', '1')이렇게
    # 그래서 html에서 주소뒤에 ?page=숫자 이런식으로 던지거나 아니면 form으로 get 방식으로 던저주는것임.

    page = request.GET.get('page', '1')  # 페이지숫자를 url서 뒤에 붙여 get으로 던짐 (?page = 1)
    kw = request.GET.get('kw', '')  # 검색어


    so = request.GET.get('so', 'recent')  # 정렬기준

    # 정렬
    if so == 'recommend':
        question_list = Question.objects.annotate(num_voter=Count('voter')).order_by('-num_voter', '-create_date')
    elif so == 'popular':
        question_list = Question.objects.annotate(num_answer=Count('answer')).order_by('-num_answer', '-create_date')
    else:  # recent
        question_list = Question.objects.order_by('-create_date')

    #정렬 기준이 추천순(recommend)인 경우에는 추천 수가 큰 것부터 정렬하므로 order_by에 추천 수 -num_voter를 입력했다.
    # 추천 수는 장고의 annotate 함수와 Count 함수를 사용.
    # Question.objects.annotate(num_voter=Count('voter'))에서 사용한 annotate 함수는
    # Question 모델의 기존 필드인 author, subject, content, create_date, modify_date, voter에 질문의
    # 추천 수에 해당하는 num_voter 필드를 임시로 추가해 주는 함수.
    # 이렇게 annotate 함수로 num_voter 필드를 추가하면 filter 함수나 order_by 함수에서
    # num_voter 필드를 사용할 수 있음.
    # 여기서 num_voter는 Count('voter')와 같이 Count 함수를 사용하여 만듦.
    # Count('voter')는 해당 질문의 추천 수이다.

#order_by('-num_voter', '-create_date')와 같이 order_by 함수에 두 개 이상의 인자가 전달되는 경우 1번째 항목부터 우선순위를 매긴다. 즉, 추천 수가 같으면 최신순으로 정렬한다.

#그리고 page, kw와 마찬가지로 템플릿에서 요청한 so값을 저장할 수 있도록 context에 so를 추가했다. 코드 수정 후 질문 목록 화면에서 정렬 기능을 사용해 보자. '인기순'으로 정렬하면 답변수가 많은 게시물부터 보여주는 것을 확인할 수 있을 것이다.

    # 조회
    question_list = Question.objects.order_by('-create_date')
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |  # 제목검색
            Q(content__icontains=kw) |  # 내용검색
            Q(author__username__icontains=kw) |  # 질문 글쓴이검색
            Q(answer__author__username__icontains=kw)  # 답변 글쓴이검색
        ).distinct()

        #  함수에 사용된 subject__icontains=kw는 제목에 kw 문자열이 포함되었는지를 의미.
        #  answer__author__username__icontains은 답변을 작성한 사람의 이름에 포함되는지를 의미.
        #  filter 함수에서 모델 필드에 접근하려면 이처럼 __를 이용하면 됨.

    # 페이징 처리
    paginator = Paginator(question_list, 10) # 페이지당 10개씩
    page_obj = paginator.get_page(page)

    context = {'question_list': page_obj, 'page': page, 'kw': kw, 'so': so}

    return render(request, 'pybo/question_list.html', context)

def detail(request, question_id):

    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}

    return render(request, 'pybo/question_detail.html', context)

pybo/views/comment_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone

from ..forms import CommentForm
from ..models import Question, Answer, Comment



@login_required(login_url='common:login')
def comment_create_question(request, question_id):
    """
    pybo 질문댓글등록
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.create_date = timezone.now()
            comment.question = question
            comment.save()
            return redirect('{}#comment_{}'.format(resolve_url('pybo:detail', question_id=comment.question.id)), comment.id )
    else:
        form = CommentForm()
    context = {'form': form}
    return render(request, 'pybo/comment_form.html', context)


@login_required(login_url='common:login')
def comment_modify_question(request, comment_id):
    """
    pybo 질문댓글수정
    """
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글수정권한이 없습니다. ')
        return redirect('pybo:detail', question_id=comment.question.id)

    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.modify_date = timezone.now()
            comment.save()
            return redirect('{}#comment_{}'.format(resolve_url('pybo:detail', question_id=comment.question.id)), comment.id )
    else:
        form = CommentForm(instance=comment)
    context = {'form': form}
    return render(request, 'pybo/comment_form.html', context)


@login_required(login_url='common:login')
def comment_delete_question(request, comment_id):
    """
    pybo 질문댓글삭제
    """
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글삭제권한이 없습니다. ')
        return redirect('pybo:detail', question_id=comment.question.id)
    else:
        comment.delete()
    return redirect('pybo:detail', question_id=comment.question.id)

@login_required(login_url='common:login')
def comment_create_answer(request, answer_id):
    """
    pybo 답글댓글등록
    """
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.create_date = timezone.now()
            comment.answer = answer
            comment.save()
            return redirect('{}#comment_{}'.format(resolve_url('pybo:detail', question_id=comment.question.id)), comment.id )
    else:
        form = CommentForm()
    context = {'form': form}
    return render(request, 'pybo/comment_form.html', context)


@login_required(login_url='common:login')
def comment_modify_answer(request, comment_id):
    """
    pybo 답글댓글수정
    """
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글수정권한이 없습니다')
        return redirect('pybo:detail', question_id=comment.answer.question.id)

    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.modify_date = timezone.now()
            comment.save()
            return redirect('{}#comment_{}'.format(resolve_url('pybo:detail', question_id=comment.question.id)), comment.id )
    else:
        form = CommentForm(instance=comment)
    context = {'form': form}
    return render(request, 'pybo/comment_form.html', context)


@login_required(login_url='common:login')
def comment_delete_answer(request, comment_id):
    """
    pybo 답글댓글삭제
    """
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글삭제권한이 없습니다')
        return redirect('pybo:detail', question_id=comment.answer.question.id)
    else:
        comment.delete()
    return redirect('pybo:detail', question_id=comment.answer.question.id)

pybo/views/vote_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect

from pybo.models import Question,Answer

@login_required(login_url='common:login')
def vote_question(request, question_id):
    """
    pybo 질문추천등록
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.user == question.author:
        messages.error(request, '본인이 작성한 글은 추천할수 없습니다')
    else:
        question.voter.add(request.user)
    return redirect('pybo:detail', question_id=question.id)


@login_required(login_url='common:login')
def vote_answer(request, answer_id):
    """
    pybo 답글추천등록
    """
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user == answer.author:
        messages.error(request, '본인이 작성한 글은 추천할수 없습니다')
    else:
        answer.voter.add(request.user)
    return redirect('pybo:detail', question_id=answer.question.id)

templates/pybo/answer_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-3">
    <form method="post" class="post-form">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="content">답변내용</label>
            <textarea class="form-control" name="content" id="content" rows="10">
                {{form.content.value|default_if_none:''}}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/pybo/comment_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-3">
    <h5 class="border-bottom pb-2">댓글등록하기</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="content">댓글내용</label>
            <textarea class="form-control"name="content" id="content" 
                      rows="3">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/pybo/question_detail.html
{% extends 'base.html' %}
{% load pybo_filter %}

{% block content %}


    <!-- 질문 제목  표시 -->

<div class="container my-3">

    <!-- 사용자 오류 표시 -->
    {% if messages %}
    <div class = "alert alert-danger my-3" role = "alert">
        {% for message in messages%}
            <strong> {{message.tags}}</strong>
            <ul><li>{{message.message}}</li></ul>
        {% endfor %}
    </div>
    {% endif %}


    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="row my-3">
        <div class="col-1"> <!-- 추천영역 -->
            <div class="bg-light text-center p-3 border font-weight-bolder mb-1">{{question.voter.count}}</div>
            <a href="#" data-uri="{% url 'pybo:vote_question' question.id  %}"
               class="recommend btn btn-sm btn-secondary btn-block my-1">추천</a>
        </div>


        <div class="col-11"> <!-- 질문영역 -->
            <div class="card">
                <div class="card-body">
                    <div class="card-text">{{ question.content|mark }}</div><!-- 마크다운 필터 적용  -->
                    <div class="d-flex justify-content-end">
                        {% if question.modify_date %}
                        <div class="badge badge-light p-2 text-left mx-3">
                            <div class="mb-2">modified at</div>
                            <div>{{ question.modify_date }}</div>
                        </div>
                        {% endif %}
                        <div class="badge badge-light p-2 text-left">
                            <div class="mb-2">{{ question.author.username }}</div>
                            <div>{{ question.create_date }}</div>
                        </div>
                    </div>
            <!-- ------------------------------- 질문 수정 및 삭제 -------------------------------- -->
             <!----로그인한 사용자와 글쓴이가 같은 경우------>
            {% if request.user == question.author %}
            <div class="my-3">
                <a href="{% url 'pybo:question_modify' question.id  %}"
                   class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="#" class="delete btn btn-sm btn-outline-secondary"
                   data-uri="{% url 'pybo:question_delete' question.id  %}">삭제</a>
            <!-- ----------------------------------------------------------------------- -->
                <!-- <삭제> 버튼을 누르면 data-uri 속성에 설정한 url이 실행 -->
            </div>
            {% endif %}

            <!-- 질문 댓글 Start -->
                    {% if question.comment_set.count > 0 %}
                    <div class="mt-3">
                    {% for comment in question.comment_set.all %}
                        <a name="comment_{{ comment.id }}"></a>

                        <div class="comment py-2 text-muted">
                            <span style="white-space: pre-line;">{{ comment.content }}</span>
                            <span>
                                - {{ comment.author }}, {{ comment.create_date }}
                                {% if comment.modify_date %}
                                (수정:{{ comment.modify_date }})
                                {% endif %}
                            </span>
                            {% if request.user == comment.author %}
                            <a href="{% url 'pybo:comment_modify_question' comment.id  %}" class="small">수정</a>,
                            <a href="#" class="small delete"
                               data-uri="{% url 'pybo:comment_delete_question' comment.id  %}">삭제</a>
                            {% endif %}
                        </div>
                    {% endfor %}
                    </div>
                    {% endif %}

                    <!-- 대댓글 추가  -->
        <div>
            <a href="{% url 'pybo:comment_create_question' question.id  %}"
               class="small"><small>대댓글 추가 ..</small></a>
        </div>

        <!-- 질문 댓글 End -->
            </div>
        </div>
    </div>
 </div>



            <!-- ------------------------------- 답변 목록  -------------------------------- -->

    <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set.all %}
    <a name="answer_{{ answer.id }}"></a>
    <div class="row my-3">
        <div class="col-1">  <!-- 추천영역 -->
            <div class="bg-light text-center p-3 border font-weight-bolder mb-1">{{answer.voter.count}}</div>
            <a href="#" data-uri="{% url 'pybo:vote_answer' answer.id  %}"
                class="recommend btn btn-sm btn-secondary btn-block my-1">추천</a>
        </div>


        <div class="col-11">  <!-- 답변영역 -->
            <div class="card">
                <div class="card-body">
                    <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
                    <div class="d-flex justify-content-end">
                        {% if answer.modify_date %}
                        <div class="badge badge-light p-2 text-left mx-3">
                            <div class="mb-2">modified at</div>
                            <div>{{ answer.modify_date }}</div>
                        </div>
                        {% endif %}
                        <div class="badge badge-light p-2 text-left">
                            <div class="mb-2">{{ answer.author.username }}</div>
                            <div>{{ answer.create_date }}</div>
                        </div>

                    </div>

             <!-- ------------------------------- 답변 수정 및 삭제 -------------------------------- -->
            {% if request.user == answer.author %}
             <div class="my-3">
                 <a href="{% url 'pybo:answer_modify' answer.id  %}"
                   class="btn btn-sm btn-outline-secondary">수정</a>
                 <a href="#" class="delete btn btn-sm btn-outline-secondary "
                   data-uri="{% url 'pybo:answer_delete' answer.id  %}">삭제</a>
            <!-- ----------------------------------------------------------------------- -->
             </div>
             {% endif %}


            <!-- -------------------------------답변의  대댓글 표시, 수정 및 삭제 -------------------------------- -->


                    {% if answer.comment_set.count > 0 %}
                    <div class="mt-3">
                    {% for comment in answer.comment_set.all %}
                        <a name="comment_{{ comment.id }}"></a>

                        <div class="comment py-2 text-muted">
                            <span style="white-space: pre-line;">{{ comment.content }}</span>
                            <span>
                                - {{ comment.author }}, {{ comment.create_date }}
                                {% if comment.modify_date %}
                                (수정:{{ comment.modify_date }})
                                {% endif %}
                            </span>
                            {% if request.user == comment.author %}
                            <a href="{% url 'pybo:comment_modify_answer' comment.id  %}" class="small">수정</a>,
                            <a href="#" class="small delete"
                               data-uri="{% url 'pybo:comment_delete_answer' comment.id  %}">삭제</a>
                            {% endif %}
                        </div>
                    {% endfor %}
                    </div>
                    {% endif %}
                    <div>
                        <a href="{% url 'pybo:comment_create_answer' answer.id  %}"
                           class="small"><small>대댓글 추가 ..</small></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}

    <!-- 댓글 작성-->
    <form action="{% url 'pybo:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
        {% for field in form %}
            {% if field.errors %}
            <strong>{{ field.label }}</strong>
            {{ field.errors }}
            {% endif %}
        {% endfor %}
        </div>
        {% endif %}
        <div class="form-group">
            <textarea {% if not user.is_authenticated %}disabled{% endif %}
              name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>

{% endblock %}
{% block script %}

<script type='text/javascript'>
    $(document).ready(function(){
        $(".delete").on('click', function() {
            if(confirm("정말로 삭제하시겠습니까?")) {
                location.href = $(this).data('uri');
            }
        });


    $(".recommend").on('click', function() {
            if(confirm("정말로 추천하시겠습니까?")) {
                location.href = $(this).data('uri');
         }
    });
});
</script>
{% endblock %}